name: My-test-workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Validate the code
        run: mvn validate

      - name: Building the code
        run: mvn clean install

      - name: Checking the artifact
        run: ls target/
